version: '3.8'

services:
  app:
    build:
      context: ./app
    command: app.py
    restart: always
    container_name: docker-test-app
    environment:
      - DATABASE_URL=postgres://postgres:qwer1234@db:5432/test_db
    volumes:
      - ./app:/app
    ports:
      - "80:5000"
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    restart: always
    container_name: docker-test-db
    hostname: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwer1234
      POSTGRES_DB: test_db
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - ./pg_db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: docker-test-pgadmin
    hostname: pgadmin
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@ksiloq.ru
      - PGADMIN_DEFAULT_PASSWORD=qwer1234
      - PGADMIN_LISTEN_PORT=80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
volumes:
  pg_db:
  pgadmin-data: